int fun() {
    ...
    error();
    throw new AssertionError("not reached");
}