try {
   ...
} catch (Exception e) {
    log.error( "failed!", e );
}